my last edits
Asel-K/ctd-react-egret pull request #2
Opened 2021-08-17 21:25 UTC by Asel-K

I've decided to go all over again through the assignment instructions and that's why had to give a new name instead of lesson-1-1.

2021-08-19 23:01 UTC, kaytiwiita requested changes
great start! showing a good understanding of what React has to offer. Just a couple quick notes to clean up the code a bit to make it more readable and condensed. Your use of the span tag is a little unnecessary since you can wrap {item.title} in the list tag. My other comments are just good coding habits to get used to.

2021-08-19 23:01 UTC, kaytijackson97 commented on src/App.js
> +
the blank lines on line 23, 28, 30, and 34 aren't needed.

2021-08-19 23:01 UTC, kaytijackson97 commented on src/App.js
> +              <span>{item.title}</span>
you can take {item.title} out of the span tags and place them between the list tags on one line.

2021-08-19 23:01 UTC, kaytijackson97 commented on src/App.js
> +      {todoList.map(function (item) {
the entire code block inside of the unordered list tags should be indented on place.

2021-08-19 23:01 UTC, kaytijackson97 commented on src/App.js
> +]
should have a semi-colon at the end of the square bracket

2021-08-21 15:35 UTC, Asel-K commented on src/App.js
> +]
Thank you for all your recommendations! very helpful. Ill try to follow them all.

2021-08-21 15:35 UTC, merged